### ISSUE TITLE
test_memcached/test_gets.py  ERROR

### ISSUE THREAD

**Issue by deep011** [idning/test-twemproxy#3]
test_memcached/test_gets.py文件中使用了get_multi(keys)函数，此函数发给twemproxy的命令是delete kkk-1 0\r\n，这样的命令twemproxy不支持，正确的用法应该是get_multi(keys, None)。
如果在编译twemproxy的时候加上--enable-debug=full，那么使用get_multi(keys)，twemproxy log中会出现如下错误：
[2015-02-10 16:19:29.153] nc_memcache.c:721 parsed bad req 393 res 1 type 3 state 17
00000000  64 65 6c 65 74 65 20 6b  6b 6b 2d 30 20 30 0d 0a   |delete kkk-0 0..|
00000010  64 65 6c 65 74 65 20 6b  6b 6b 2d 31 20 30 0d 0a   |delete kkk-1 0..|
00000020  64 65 6c 65 74 65 20 6b  6b 6b 2d 32 20 30 0d 0a   |delete kkk-2 0..|
00000030  64 65 6c 65 74 65 20 6b  6b 6b 2d 33 20 30 0d 0a   |delete kkk-3 0..|
00000040  64 65 6c 65 74 65 20 6b  6b 6b 2d 34 20 30 0d 0a   |delete kkk-4 0..|
00000050  64 65 6c 65 74 65 20 6b  6b 6b 2d 35 20 30 0d 0a   |delete kkk-5 0..|
00000060  64 65 6c 65 74 65 20 6b  6b 6b 2d 36 20 30 0d 0a   |delete kkk-6 0..|
00000070  64 65 6c 65 74 65 20 6b  6b 6b 2d 37 20 30 0d 0a   |delete kkk-7 0..|
00000080  64 65 6c 65 74 65 20 6b  6b 6b 2d 38 20 30 0d 0a   |delete kkk-8 0..|
00000090  64 65 6c 65 74 65 20 6b  6b 6b 2d 39 20 30 0d 0a   |delete kkk-9 0..|
[2015-02-10 16:19:29.153] nc_core.c:198 recv on c 9 failed: Invalid argument

**Comment by idning** [comment]
这个问题讨论过，python的memcache的协议实现有问题, 使用的是老的协议版本:

https://github.com/twitter/twemproxy/pull/300
